version: '3.8'

services:
  # Web version for AWS deployment
  car_dealer_web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: ol_service_web
    restart: unless-stopped
    volumes:
      - ./vehicle_photos:/app/vehicle_photos
      - ./data:/app/data
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - web

  # Add nginx for production
  nginx:
    image: nginx:alpine
    container_name: ol_service_nginx
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
      # For SSL certificates
      # - ./certbot/conf:/etc/letsencrypt
      # - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - ol_service_web
    networks:
      - web

  # Optional: Add certbot for SSL
  # certbot:
  #   image: certbot/certbot
  #   container_name: ol_service_certbot
  #   volumes:
  #     - ./certbot/conf:/etc/letsencrypt
  #     - ./certbot/www:/var/www/certbot
  #   entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  web:
    driver: bridge